limeData = [
    {
        "id": 1,
        "name": "Lime",
        "species": "Citrus aurantiifolia",
        "type": "Citrus Fruit",
        "category": "Fruit",
        "sunlight": "Full Sun",
        "water": "Moderate",
        "soil": "Well-draining",
        "growthRate": "Moderate",
        "origin": "Southeast Asia",
        "generation": "Genus: Citrus, Family: Rutaceae",
        "description": "Lime is a small, green citrus fruit known for its tangy, acidic flavor. It's commonly used in cooking, beverages, and as a garnish. The plant is adapted to full sun and well-draining soil.",
        "image": "./img/lime.JGP",
        "Price": "RS: 6,150"
    },
    {
        "id": 2,
        "name": "Orange",
        "species": "Citrus sinensis",
        "type": "Citrus Fruit",
        "category": "Fruit",
        "sunlight": "Full Sun",
        "water": "Moderate",
        "soil": "Well-draining",
        "growthRate": "Moderate to Fast",
        "origin": "Southeast Asia",
        "generation": "Genus: Citrus, Family: Rutaceae",
        "description": "Orange is a popular citrus fruit known for its sweet and tangy flavor. It is widely consumed fresh or as juice. The orange tree requires full sun and well-draining soil to thrive.",
        "image": "./img/orange.webp",
        "Price": "RS: 4,480"
    },
    {
        "id": 3,
        "name": "Grapefruit",
        "species": "Citrus paradisi",
        "type": "Citrus Fruit",
        "category": "Fruit",
        "sunlight": "Full Sun",
        "water": "Moderate",
        "soil": "Well-draining",
        "growthRate": "Moderate",
        "origin": "Barbados",
        "generation": "Genus: Citrus, Family: Rutaceae",
        "description": "Grapefruit is a citrus fruit known for its tangy, slightly bitter flavor and high vitamin C content. It grows best in full sun and requires well-draining soil.",
        "image": "./img/orange.webp",
        "Price": "RS: 4,000"
    },
    {
        "id": 4,
        "name": "Mandarin",
        "species": "Citrus reticulata",
        "type": "Citrus Fruit",
        "category": "Fruit",
        "sunlight": "Full Sun",
        "water": "Moderate",
        "soil": "Well-draining",
        "growthRate": "Moderate",
        "origin": "China",
        "generation": "Genus: Citrus, Family: Rutaceae",
        "description": "Mandarin is a small, sweet citrus fruit known for its easy-to-peel skin and juicy segments. It thrives in full sun and well-draining soil.",
        "image": "./img/orange.webp",
        "Price": "RS: 4,000"
    },
    {
        "id": 5,
        "name": "Tangerine",
        "species": "Citrus tangerina",
        "type": "Citrus Fruit",
        "category": "Fruit",
        "sunlight": "Full Sun",
        "water": "Moderate",
        "soil": "Well-draining",
        "growthRate": "Moderate",
        "origin": "Japan",
        "generation": "Genus: Citrus, Family: Rutaceae",
        "description": "Tangerine is a small citrus fruit known for its bright orange color and sweet, tangy flavor. It is easy to peel and segments are juicy. The plant prefers full sun and well-draining soil.",
        "image": "https://example.com/tangerine.jpg"
    },{
        "id": 6,
        "name": "Pomelo",
        "species": "Citrus maxima",
        "type": "Citrus Fruit",
        "category": "Fruit",
        "sunlight": "Full Sun",
        "water": "Moderate",
        "soil": "Well-draining",
        "growthRate": "Slow to Moderate",
        "origin": "Southeast Asia",
        "generation": "Genus: Citrus, Family: Rutaceae",
        "description": "Pomelo is the largest citrus fruit known for its thick, green or yellow skin and sweet, mildly tangy flesh. It grows best in full sun and well-draining soil.",
        "image": "https://example.com/pomelo.jpg"
    },{
        "id": 7,
        "name": "Bergamot Orange",
        "species": "Citrus bergamia",
        "type": "Citrus Fruit",
        "category": "Fruit",
        "sunlight": "Full Sun",
        "water": "Moderate",
        "soil": "Well-draining",
        "growthRate": "Slow to Moderate",
        "origin": "Italy",
        "generation": "Genus: Citrus, Family: Rutaceae",
        "description": "Bergamot orange is a citrus fruit known for its distinct, aromatic flavor and essential oils used in perfumes and Earl Grey tea. It requires full sun and well-draining soil to thrive.",
        "image": "https://example.com/bergamot-orange.jpg"
    },{
        "id": 8,
        "name": "Kumquat",
        "species": "Fortunella margarita",
        "type": "Citrus Fruit",
        "category": "Fruit",
        "sunlight": "Full Sun",
        "water": "Moderate",
        "soil": "Well-draining",
        "growthRate": "Slow to Moderate",
        "origin": "China",
        "generation": "Genus: Fortunella, Family: Rutaceae",
        "description": "Kumquat is a small citrus fruit known for its sweet and tangy flavor, and edible skin. It thrives in full sun and well-draining soil.",
        "image": "https://example.com/kumquat.jpg"
    },{
        "id": 9,
        "name": "Citron",
        "species": "Citrus medica",
        "type": "Citrus Fruit",
        "category": "Fruit",
        "sunlight": "Full Sun",
        "water": "Moderate",
        "soil": "Well-draining",
        "growthRate": "Slow to Moderate",
        "origin": "India and China",
        "generation": "Genus: Citrus, Family: Rutaceae",
        "description": "Citron is a large, yellow citrus fruit with a thick, rough skin and a lemon-like aroma. It is often used in preserves and as a flavoring. The plant requires full sun and well-draining soil.",
        "image": "https://example.com/citron.jpg"
    },{
        "id": 10,
        "name": "Bitter Orange",
        "species": "Citrus aurantium",
        "type": "Citrus Fruit",
        "category": "Fruit",
        "sunlight": "Full Sun",
        "water": "Moderate",
        "soil": "Well-draining",
        "growthRate": "Moderate",
        "origin": "Southeast Asia",
        "generation": "Genus: Citrus, Family: Rutaceae",
        "description": "Bitter orange is a citrus fruit known for its sharp, tangy flavor and bitter taste. It is used in marmalade, liqueurs, and traditional medicine. The plant thrives in full sun and well-draining soil.",
        "image": "https://example.com/bitter-orange.jpg"
    },{
        "id": 11,
        "name": "Calamondin",
        "species": "Citrus microcarpa",
        "type": "Citrus Fruit",
        "category": "Fruit",
        "sunlight": "Full Sun",
        "water": "Moderate",
        "soil": "Well-draining",
        "growthRate": "Moderate",
        "origin": "Philippines",
        "generation": "Genus: Citrus, Family: Rutaceae",
        "description": "Calamondin is a small citrus fruit with a tart flavor and thin, orange skin. It is often used in Filipino cuisine and as a decorative plant. It grows best in full sun and well-draining soil.",
        "image": "https://example.com/calamondin.jpg"
    },{
        "id": 12,
        "name": "Kaffir Lime",
        "species": "Citrus hystrix",
        "type": "Citrus Fruit",
        "category": "Fruit",
        "sunlight": "Full Sun",
        "water": "Moderate",
        "soil": "Well-draining",
        "growthRate": "Moderate",
        "origin": "Southeast Asia",
        "generation": "Genus: Citrus, Family: Rutaceae",
        "description": "Kaffir lime is known for its aromatic leaves and distinct, bumpy fruit. The zest and leaves are commonly used in Southeast Asian cuisine for their unique flavor. The plant prefers full sun and well-draining soil.",
        "image": "https://example.com/kaffir-lime.jpg"
    },{
        "id": 13,
        "name": "Yuzu",
        "species": "Citrus junos",
        "type": "Citrus Fruit",
        "category": "Fruit",
        "sunlight": "Full Sun",
        "water": "Moderate",
        "soil": "Well-draining",
        "growthRate": "Slow to Moderate",
        "origin": "East Asia",
        "generation": "Genus: Citrus, Family: Rutaceae",
        "description": "Yuzu is a citrus fruit with a distinct tart and aromatic flavor, often used in Japanese cuisine and as a flavoring in various dishes and beverages. The plant thrives in full sun and well-draining soil.",
        "image": "https://example.com/yuzu.jpg"
    },{
        "id": 14,
        "name": "Sudachi",
        "species": "Citrus sudachi",
        "type": "Citrus Fruit",
        "category": "Fruit",
        "sunlight": "Full Sun",
        "water": "Moderate",
        "soil": "Well-draining",
        "growthRate": "Slow to Moderate",
        "origin": "Japan",
        "generation": "Genus: Citrus, Family: Rutaceae",
        "description": "Sudachi is a small, green citrus fruit known for its tart flavor and aromatic zest. It is often used in Japanese cuisine, particularly in sauces and dressings. The plant grows best in full sun and well-draining soil.",
        "image": "https://example.com/sudachi.jpg"
    },{
        "id": 15,
        "name": "Kinkan",
        "species": "Fortunella japonica",
        "type": "Citrus Fruit",
        "category": "Fruit",
        "sunlight": "Full Sun",
        "water": "Moderate",
        "soil": "Well-draining",
        "growthRate": "Slow to Moderate",
        "origin": "Japan",
        "generation": "Genus: Fortunella, Family: Rutaceae",
        "description": "Kinkan, also known as kumquat, is a small citrus fruit with a sweet and tangy flavor. The fruit's skin is edible and contributes to its unique taste. It prefers full sun and well-draining soil.",
        "image": "https://example.com/kinkan.jpg"
    },{
        "id": 16,
        "name": "Clementine",
        "species": "Citrus clementina",
        "type": "Citrus Fruit",
        "category": "Fruit",
        "sunlight": "Full Sun",
        "water": "Moderate",
        "soil": "Well-draining",
        "growthRate": "Moderate",
        "origin": "Algeria",
        "generation": "Genus: Citrus, Family: Rutaceae",
        "description": "Clementine is a small, sweet citrus fruit known for its easy-to-peel skin and juicy segments. It is often enjoyed fresh or as a snack. The plant thrives in full sun and well-draining soil.",
        "image": "https://example.com/clementine.jpg"
    },{
        "id": 17,
        "name": "Seville Orange",
        "species": "Citrus aurantium",
        "type": "Citrus Fruit",
        "category": "Fruit",
        "sunlight": "Full Sun",
        "water": "Moderate",
        "soil": "Well-draining",
        "growthRate": "Moderate",
        "origin": "Spain",
        "generation": "Genus: Citrus, Family: Rutaceae",
        "description": "Seville orange, also known as bitter orange, is renowned for its tart flavor and is commonly used in marmalade and as a flavoring. It prefers full sun and well-draining soil.",
        "image": "https://example.com/seville-orange.jpg"
    },{
        "id": 18,
        "name": "Mandarins",
        "species": "Citrus reticulata",
        "type": "Citrus Fruit",
        "category": "Fruit",
        "sunlight": "Full Sun",
        "water": "Moderate",
        "soil": "Well-draining",
        "growthRate": "Moderate",
        "origin": "China",
        "generation": "Genus: Citrus, Family: Rutaceae",
        "description": "Mandarins are small, sweet citrus fruits known for their easy-to-peel skin and juicy segments. They are often enjoyed fresh or used in cooking and desserts. The plant thrives in full sun and well-draining soil.",
        "image": "https://example.com/mandarins.jpg"
    },{
        "id": 19,
        "name": "Finger Lime",
        "species": "Citrus australasica",
        "type": "Citrus Fruit",
        "category": "Fruit",
        "sunlight": "Full Sun",
        "water": "Moderate",
        "soil": "Well-draining",
        "growthRate": "Slow to Moderate",
        "origin": "Australia",
        "generation": "Genus: Citrus, Family: Rutaceae",
        "description": "Finger lime is a unique citrus fruit known for its elongated shape and caviar-like vesicles that burst with tangy juice. It is used in gourmet dishes and as a garnish. The plant thrives in full sun and well-draining soil.",
        "image": "https://example.com/finger-lime.jpg"
    },{
        "id": 20,
        "name": "Rangpur Lime",
        "species": "Citrus limonia",
        "type": "Citrus Fruit",
        "category": "Fruit",
        "sunlight": "Full Sun",
        "water": "Moderate",
        "soil": "Well-draining",
        "growthRate": "Moderate",
        "origin": "India",
        "generation": "Genus: Citrus, Family: Rutaceae",
        "description": "Rangpur lime is a citrus fruit known for its orange skin and acidic, tangy flavor. It is often used in cooking and as a flavoring agent. The plant requires full sun and well-draining soil to thrive.",
        "image": "https://example.com/rangpur-lime.jpg"
    },{
        "id": 21,
        "name": "Sweet Lemon",
        "species": "Citrus limetta",
        "type": "Citrus Fruit",
        "category": "Fruit",
        "sunlight": "Full Sun",
        "water": "Moderate",
        "soil": "Well-draining",
        "growthRate": "Moderate",
        "origin": "India",
        "generation": "Genus: Citrus, Family: Rutaceae",
        "description": "Sweet lemon, also known as sweet lime, is a citrus fruit with a mild, sweet flavor and low acidity. It is often consumed fresh or as juice. The plant prefers full sun and well-draining soil.",
        "image": "https://example.com/sweet-lemon.jpg"
    },{
        "id": 22,
        "name": "Limequat",
        "species": "Fortunella Citrus",
        "type": "Citrus Fruit",
        "category": "Fruit",
        "sunlight": "Full Sun",
        "water": "Moderate",
        "soil": "Well-draining",
        "growthRate": "Moderate",
        "origin": "Hybrid (Citrus and Fortunella species)",
        "generation": "Genus: Fortunella Citrus, Family: Rutaceae",
        "description": "Limequat is a hybrid citrus fruit combining lime and kumquat traits. It is small, tart, and has an edible skin. It is used in various culinary applications. The plant requires full sun and well-draining soil.",
        "image": "https://example.com/limequat.jpg"
    },{
        "id": 23,
        "name": "Ichang Papeda",
        "species": "Citrus ichangensis",
        "type": "Citrus Fruit",
        "category": "Fruit",
        "sunlight": "Full Sun",
        "water": "Moderate",
        "soil": "Well-draining",
        "growthRate": "Slow to Moderate",
        "origin": "China",
        "generation": "Genus: Citrus, Family: Rutaceae",
        "description": "Ichang papeda is a citrus fruit known for its hardy nature and distinctive, tart flavor. It is used in breeding programs to develop more cold-tolerant citrus varieties. The plant prefers full sun and well-draining soil.",
        "image": "https://example.com/ichang-papeda.jpg"
    },{
        "id": 24,
        "name": "Oroblanco",
        "species": "Citrus × grandis",
        "type": "Citrus Fruit",
        "category": "Fruit",
        "sunlight": "Full Sun",
        "water": "Moderate",
        "soil": "Well-draining",
        "growthRate": "Moderate",
        "origin": "United States (Hybrid)",
        "generation": "Genus: Citrus, Family: Rutaceae",
        "description": "Oroblanco, also known as sweetie, is a hybrid citrus fruit with a sweet and mildly tangy flavor. It has a thick, pale green skin and is often enjoyed fresh. The plant thrives in full sun and well-draining soil.",
        "image": "https://example.com/oroblanco.jpg"
    },{
        "id": 25,
        "name": "Sweetie",
        "species": "Citrus × grandis",
        "type": "Citrus Fruit",
        "category": "Fruit",
        "sunlight": "Full Sun",
        "water": "Moderate",
        "soil": "Well-draining",
        "growthRate": "Moderate",
        "origin": "United States (Hybrid)",
        "generation": "Genus: Citrus, Family: Rutaceae",
        "description": "Sweetie, also known as oroblanco, is a hybrid citrus fruit with a sweet and mildly tangy flavor. It features a thick, pale green skin and is often enjoyed fresh. The plant prefers full sun and well-draining soil.",
        "image": "https://example.com/sweetie.jpg"
    },    {
        "id": 26,
        "name": "Djeruk Limau",
        "species": "Citrus limau",
        "type": "Citrus Fruit",
        "category": "Fruit",
        "sunlight": "Full Sun",
        "water": "Moderate",
        "soil": "Well-draining",
        "growthRate": "Moderate",
        "origin": "Southeast Asia",
        "generation": "Genus: Citrus, Family: Rutaceae",
        "description": "Djeruk Limau, also known as lime or calamansi, is a small citrus fruit with a tart flavor, commonly used in Southeast Asian cuisine. It thrives in full sun and well-draining soil.",
        "image": "https://example.com/djeruk-limau.jpg"
    },{
        "id": 27,
        "name": "Sweet Orange",
        "species": "Citrus sinensis",
        "type": "Citrus Fruit",
        "category": "Fruit",
        "sunlight": "Full Sun",
        "water": "Moderate",
        "soil": "Well-draining",
        "growthRate": "Moderate",
        "origin": "China",
        "generation": "Genus: Citrus, Family: Rutaceae",
        "description": "Sweet orange is a popular citrus fruit known for its juicy, sweet segments and vibrant color. It is commonly enjoyed fresh or as juice. The plant thrives in full sun and well-draining soil.",
        "image": "https://example.com/sweet-orange.jpg"
    },{
        "id": 28,
        "name": "Trifoliate Orange",
        "species": "Poncirus trifoliata",
        "type": "Citrus Fruit",
        "category": "Fruit",
        "sunlight": "Full Sun",
        "water": "Moderate",
        "soil": "Well-draining",
        "growthRate": "Slow to Moderate",
        "origin": "China",
        "generation": "Genus: Poncirus, Family: Rutaceae",
        "description": "Trifoliate orange is a hardy citrus fruit known for its trifoliate leaves and small, sour fruit. It is often used as a rootstock for other citrus trees due to its cold tolerance. The plant prefers full sun and well-draining soil.",
        "image": "https://example.com/trifoliate-orange.jpg"
    },{
        "id": 29,
        "name": "Meyer Lemon",
        "species": "Citrus × meyeri",
        "type": "Citrus Fruit",
        "category": "Fruit",
        "sunlight": "Full Sun",
        "water": "Moderate",
        "soil": "Well-draining",
        "growthRate": "Moderate",
        "origin": "China",
        "generation": "Genus: Citrus, Family: Rutaceae",
        "description": "Meyer lemon is a sweet and aromatic lemon variety with a thin, bright yellow skin and a milder flavor compared to standard lemons. It is commonly used in cooking and baking. The plant prefers full sun and well-draining soil.",
        "image": "https://example.com/meyer-lemon.jpg"
    },{
        "id": 30,
        "name": "Citrange",
        "species": "Citrus × sinensis × Poncirus trifoliata",
        "type": "Citrus Fruit",
        "category": "Fruit",
        "sunlight": "Full Sun",
        "water": "Moderate",
        "soil": "Well-draining",
        "growthRate": "Moderate",
        "origin": "Hybrid (United States)",
        "generation": "Genus: Citrus, Family: Rutaceae",
        "description": "Citrange is a hybrid citrus fruit resulting from the cross between sweet orange and trifoliate orange. It combines the sweetness of oranges with the hardiness of trifoliate orange. The plant thrives in full sun and well-draining soil.",
        "image": "https://example.com/citrange.jpg"
    },{
        "id": 31,
        "name": "Kaffir Lime",
        "species": "Citrus hystrix",
        "type": "Citrus Fruit",
        "category": "Fruit",
        "sunlight": "Full Sun",
        "water": "Moderate",
        "soil": "Well-draining",
        "growthRate": "Moderate",
        "origin": "Southeast Asia",
        "generation": "Genus: Citrus, Family: Rutaceae",
        "description": "Kaffir lime is known for its aromatic leaves and distinct, bumpy fruit. The zest and leaves are commonly used in Southeast Asian cuisine for their unique flavor. The plant prefers full sun and well-draining soil.",
        "image": "https://example.com/kaffir-lime.jpg"
    },{
        "id": 32,
        "name": "Buddha's Hand",
        "species": "Citrus medica",
        "type": "Citrus Fruit",
        "category": "Fruit",
        "sunlight": "Full Sun",
        "water": "Moderate",
        "soil": "Well-draining",
        "growthRate": "Slow to Moderate",
        "origin": "China",
        "generation": "Genus: Citrus, Family: Rutaceae",
        "description": "Buddha's Hand is a unique citrus fruit known for its finger-like segments resembling a hand in prayer. It is highly aromatic and used primarily for its zest and as a decorative element. The plant thrives in full sun and well-draining soil.",
        "image": "https://example.com/buddhas-hand.jpg"
    },{
        "id": 33,
        "name": "Sweet Orange",
        "species": "Citrus sinensis",
        "type": "Citrus Fruit",
        "category": "Fruit",
        "sunlight": "Full Sun",
        "water": "Moderate",
        "soil": "Well-draining",
        "growthRate": "Moderate",
        "origin": "China",
        "generation": "Genus: Citrus, Family: Rutaceae",
        "description": "Sweet orange is a popular citrus fruit known for its juicy, sweet segments and vibrant color. It is commonly enjoyed fresh or as juice. The plant thrives in full sun and well-draining soil.",
        "image": "https://example.com/sweet-orange.jpg"
    },{
        "id": 34,
        "name": "Navel Orange",
        "species": "Citrus sinensis",
        "type": "Citrus Fruit",
        "category": "Fruit",
        "sunlight": "Full Sun",
        "water": "Moderate",
        "soil": "Well-draining",
        "growthRate": "Moderate",
        "origin": "Brazil",
        "generation": "Genus: Citrus, Family: Rutaceae",
        "description": "Navel orange is a seedless variety of sweet orange, known for its large size and easy-to-peel skin. It has a sweet, juicy flavor and is commonly eaten fresh or used in juices. The plant thrives in full sun and well-draining soil.",
        "image": "https://example.com/navel-orange.jpg"
    },{
        "id": 35,
        "name": "Bergamot Lime",
        "species": "Citrus bergamia",
        "type": "Citrus Fruit",
        "category": "Fruit",
        "sunlight": "Full Sun",
        "water": "Moderate",
        "soil": "Well-draining",
        "growthRate": "Moderate",
        "origin": "Italy",
        "generation": "Genus: Citrus, Family: Rutaceae",
        "description": "Bergamot lime is known for its distinctive, aromatic flavor and is primarily used in flavoring tea and perfumes. It has a tart taste and a greenish-yellow skin. The plant thrives in full sun and well-draining soil.",
        "image": "https://example.com/bergamot-lime.jpg"
    },{
        "id": 36,
        "name": "Pomelo Grapefruit",
        "species": "Citrus × grandis",
        "type": "Citrus Fruit",
        "category": "Fruit",
        "sunlight": "Full Sun",
        "water": "Moderate",
        "soil": "Well-draining",
        "growthRate": "Moderate",
        "origin": "Hybrid (United States)",
        "generation": "Genus: Citrus, Family: Rutaceae",
        "description": "Pomelo grapefruit, also known as oroblanco, is a hybrid citrus fruit that combines the characteristics of pomelo and grapefruit. It has a sweet and mildly tangy flavor, with a thick, pale rind. The plant prefers full sun and well-draining soil.",
        "image": "https://example.com/pomelo-grapefruit.jpg"
    },{
        "id": 37,
        "name": "Yuzu",
        "species": "Citrus junos",
        "type": "Citrus Fruit",
        "category": "Fruit",
        "sunlight": "Full Sun",
        "water": "Moderate",
        "soil": "Well-draining",
        "growthRate": "Slow to Moderate",
        "origin": "Japan",
        "generation": "Genus: Citrus, Family: Rutaceae",
        "description": "Yuzu is a citrus fruit known for its unique, aromatic flavor that combines tartness with floral notes. It is widely used in Japanese cuisine and beverages. The plant requires full sun and well-draining soil to thrive.",
        "image": "https://example.com/yuzu.jpg"
    },{
        "id": 38,
        "name": "Rangpur Lime",
        "species": "Citrus × limonia",
        "type": "Citrus Fruit",
        "category": "Fruit",
        "sunlight": "Full Sun",
        "water": "Moderate",
        "soil": "Well-draining",
        "growthRate": "Moderate",
        "origin": "India",
        "generation": "Genus: Citrus, Family: Rutaceae",
        "description": "Rangpur lime is a hybrid citrus fruit known for its sour taste and vibrant orange skin. It is used in cooking and beverages, and is valued for its high acidity and distinctive flavor. The plant thrives in full sun and well-draining soil.",
        "image": "https://example.com/rangpur-lime.jpg"
    },{
        "id": 39,
        "name": "Kumquat Orange",
        "species": "Fortunella",
        "type": "Citrus Fruit",
        "category": "Fruit",
        "sunlight": "Full Sun",
        "water": "Moderate",
        "soil": "Well-draining",
        "growthRate": "Moderate",
        "origin": "China",
        "generation": "Genus: Fortunella, Family: Rutaceae",
        "description": "Kumquat orange is a small citrus fruit with a sweet and tart flavor. It has a thin, edible skin and is often eaten whole. The plant is hardy and thrives in full sun and well-draining soil.",
        "image": "https://example.com/kumquat-orange.jpg"
    },{
        "id": 40,
        "name": "Tangelo",
        "species": "Citrus × tangelo",
        "type": "Citrus Fruit",
        "category": "Fruit",
        "sunlight": "Full Sun",
        "water": "Moderate",
        "soil": "Well-draining",
        "growthRate": "Moderate",
        "origin": "United States (Hybrid)",
        "generation": "Genus: Citrus, Family: Rutaceae",
        "description": "Tangelo is a hybrid citrus fruit that combines the sweet flavor of tangerines with the tangy zest of grapefruits. It has a juicy, aromatic flavor and is easy to peel. The plant thrives in full sun and well-draining soil.",
        "image": "https://example.com/tangelo.jpg"
    },{
        "id": 41,
        "name": "Clementine",
        "species": "Citrus clementina",
        "type": "Citrus Fruit",
        "category": "Fruit",
        "sunlight": "Full Sun",
        "water": "Moderate",
        "soil": "Well-draining",
        "growthRate": "Moderate",
        "origin": "Algeria",
        "generation": "Genus: Citrus, Family: Rutaceae",
        "description": "Clementine is a small, sweet citrus fruit known for its easy-to-peel skin and juicy segments. It is a popular snack and is used in various recipes. The plant thrives in full sun and well-draining soil.",
        "image": "https://example.com/clementine.jpg"
    },{
        "id": 42,
        "name": "Noble Mandarin",
        "species": "Citrus nobilis",
        "type": "Citrus Fruit",
        "category": "Fruit",
        "sunlight": "Full Sun",
        "water": "Moderate",
        "soil": "Well-draining",
        "growthRate": "Moderate",
        "origin": "China",
        "generation": "Genus: Citrus, Family: Rutaceae",
        "description": "Citrus nobilis, commonly known as the noble mandarin, is a citrus fruit valued for its sweet, easy-to-peel segments. It is commonly eaten fresh or used in cooking. The plant requires full sun and well-draining soil to thrive.",
        "image": "https://example.com/noble-mandarin.jpg"
    },{
        "id": 43,
        "name": "Citron",
        "species": "Citrus medica",
        "type": "Citrus Fruit",
        "category": "Fruit",
        "sunlight": "Full Sun",
        "water": "Moderate",
        "soil": "Well-draining",
        "growthRate": "Slow to Moderate",
        "origin": "India",
        "generation": "Genus: Citrus, Family: Rutaceae",
        "description": "Citron is a large, yellow citrus fruit with a thick, bumpy rind and a tart flavor. It is used in cooking, as a flavoring, and in religious rituals. The plant thrives in full sun and well-draining soil.",
        "image": "https://example.com/citron.jpg"
    },{
        "id": 44,
        "name": "Kumquat",
        "species": "Citrus japonica",
        "type": "Citrus Fruit",
        "category": "Fruit",
        "sunlight": "Full Sun",
        "water": "Moderate",
        "soil": "Well-draining",
        "growthRate": "Moderate",
        "origin": "China",
        "generation": "Genus: Citrus, Family: Rutaceae",
        "description": "Kumquat, also known as Citrus japonica, is a small citrus fruit with a sweet and tart flavor. It has a thin, edible skin and is often eaten whole or used in preserves and cooking. The plant prefers full sun and well-draining soil.",
        "image": "https://example.com/kumquat.jpg"
    },{
        "id": 45,
        "name": "Grapefruit Orange",
        "species": "Citrus × paradisi",
        "type": "Citrus Fruit",
        "category": "Fruit",
        "sunlight": "Full Sun",
        "water": "Moderate",
        "soil": "Well-draining",
        "growthRate": "Moderate",
        "origin": "Barbados",
        "generation": "Genus: Citrus, Family: Rutaceae",
        "description": "Grapefruit orange is a citrus fruit known for its tart flavor and large size. It has a thick, yellow to pink rind and is commonly enjoyed fresh or as juice. The plant thrives in full sun and well-draining soil.",
        "image": "https://example.com/grapefruit-orange.jpg"
    }, {
        "id": 46,
        "name": "Lime Orange",
        "species": "Citrus × latifolia",
        "type": "Citrus Fruit",
        "category": "Fruit",
        "sunlight": "Full Sun",
        "water": "Moderate",
        "soil": "Well-draining",
        "growthRate": "Moderate",
        "origin": "Hybrid (United States)",
        "generation": "Genus: Citrus, Family: Rutaceae",
        "description": "Lime orange, also known as Persian lime, is a hybrid citrus fruit that combines the tangy flavor of limes with the size of oranges. It has a green rind and is commonly used in cooking and beverages. The plant requires full sun and well-draining soil.",
        "image": "https://example.com/lime-orange.jpg"
    },{
        "id": 47,
        "name": "Mandarin Orange",
        "species": "Citrus reticulata",
        "type": "Citrus Fruit",
        "category": "Fruit",
        "sunlight": "Full Sun",
        "water": "Moderate",
        "soil": "Well-draining",
        "growthRate": "Moderate",
        "origin": "China",
        "generation": "Genus: Citrus, Family: Rutaceae",
        "description": "Mandarin orange, known scientifically as Citrus reticulata, is a small citrus fruit prized for its sweet, easy-to-peel segments. It is commonly enjoyed fresh or used in a variety of dishes. The plant thrives in full sun and well-draining soil.",
        "image": "https://example.com/mandarin-orange.jpg"
    },{
        "id": 48,
        "name": "Kaffir Lime",
        "species": "Citrus hystrix",
        "type": "Citrus Fruit",
        "category": "Fruit",
        "sunlight": "Full Sun",
        "water": "Moderate",
        "soil": "Well-draining",
        "growthRate": "Moderate",
        "origin": "Southeast Asia",
        "generation": "Genus: Citrus, Family: Rutaceae",
        "description": "Kaffir lime is valued for its aromatic leaves and distinctive, bumpy fruit. It is widely used in Southeast Asian cuisine for its unique flavor. The plant thrives in full sun and well-draining soil.",
        "image": "https://example.com/kaffir-lime.jpg"
    },                      {
        "id": 49,
        "name": "Rough Lemon",
        "species": "Citrus × tomentosa",
        "type": "Citrus Fruit",
        "category": "Fruit",
        "sunlight": "Full Sun",
        "water": "Moderate",
        "soil": "Well-draining",
        "growthRate": "Moderate",
        "origin": "Hybrid (India)",
        "generation": "Genus: Citrus, Family: Rutaceae",
        "description": "Rough lemon, also known as Citrus × tomentosa, is a hybrid citrus fruit known for its rough, bumpy skin and sour flavor. It is often used as a rootstock for other citrus plants and occasionally in culinary applications. The plant prefers full sun and well-draining soil.",
        "image": "https://example.com/rough-lemon.jpg"
    },{
        "id": 50,
        "name": "Bitter Orange",
        "species": "Citrus × aurantium",
        "type": "Citrus Fruit",
        "category": "Fruit",
        "sunlight": "Full Sun",
        "water": "Moderate",
        "soil": "Well-draining",
        "growthRate": "Moderate",
        "origin": "Asia",
        "generation": "Genus: Citrus, Family: Rutaceae",
        "description": "Bitter orange, also known as Seville orange, is a citrus fruit known for its tart and bitter flavor. It is often used in marmalades, liqueurs, and as a flavoring in various culinary dishes. The plant thrives in full sun and well-draining soil.",
        "image": "https://example.com/bitter-orange.jpg"
    }                             
];


mangoData = [
    {
        "id": 51,
        "name": "Sindhri Mango",
        "species": "Mangifera indica",
        "type": "Fruit",
        "category": "Tropical Fruit",
        "sunlight": "Full Sun",
        "water": "Moderate",
        "soil": "Well-draining",
        "growthRate": "Moderate",
        "origin": "Pakistan",
        "generation": "Genus: Mangifera, Family: Anacardiaceae",
        "description": "Sindhri mango is celebrated for its large size, sweet flavor, and juicy, fiberless flesh. It has a golden-yellow skin when ripe and is highly valued for its aromatic and rich taste. The plant thrives in full sun and well-draining soil.",
        "image": "https://example.com/sindhri-mango.jpg"
    }, {
        "id": 52,
        "name": "Chaunsa Mango",
        "species": "Mangifera indica",
        "type": "Fruit",
        "category": "Tropical Fruit",
        "sunlight": "Full Sun",
        "water": "Moderate",
        "soil": "Well-draining",
        "growthRate": "Moderate",
        "origin": "India",
        "generation": "Genus: Mangifera, Family: Anacardiaceae",
        "description": "Chaunsa mango is highly prized for its exceptionally sweet, rich flavor and smooth, juicy texture. It has a golden-yellow skin with a slight blush when ripe and is considered one of the best mango varieties. The plant requires full sun and well-draining soil to thrive.",
        "image": "https://example.com/chaunsa-mango.jpg"
    },{
        "id": 53,
        "name": "Langra Mango",
        "species": "Mangifera indica",
        "type": "Fruit",
        "category": "Tropical Fruit",
        "sunlight": "Full Sun",
        "water": "Moderate",
        "soil": "Well-draining",
        "growthRate": "Moderate",
        "origin": "India",
        "generation": "Genus: Mangifera, Family: Anacardiaceae",
        "description": "Langra mango is known for its distinctive flavor and smooth, fiberless texture. It has a green skin that turns yellow when ripe and is highly valued for its sweet, tangy taste. The plant thrives in full sun and well-draining soil.",
        "image": "https://example.com/langra-mango.jpg"
    },{
        "id": 54,
        "name": "Dusheri Mango",
        "species": "Mangifera indica",
        "type": "Fruit",
        "category": "Tropical Fruit",
        "sunlight": "Full Sun",
        "water": "Moderate",
        "soil": "Well-draining",
        "growthRate": "Moderate",
        "origin": "India",
        "generation": "Genus: Mangifera, Family: Anacardiaceae",
        "description": "Dusheri mango is celebrated for its sweet, tangy flavor and rich, creamy texture. It has a vibrant yellow skin with a hint of red when ripe and is highly valued for its aromatic taste. The plant thrives in full sun and well-draining soil.",
        "image": "https://example.com/dusheri-mango.jpg"
    },{
        "id": 55,
        "name": "Anwar Ratol Mango",
        "species": "Mangifera indica",
        "type": "Fruit",
        "category": "Tropical Fruit",
        "sunlight": "Full Sun",
        "water": "Moderate",
        "soil": "Well-draining",
        "growthRate": "Moderate",
        "origin": "Pakistan",
        "generation": "Genus: Mangifera, Family: Anacardiaceae",
        "description": "Anwar Ratol mango is known for its small size, exceptional sweetness, and aromatic flavor. It has a yellow skin when ripe and is highly prized for its rich taste and minimal fiber. The plant thrives in full sun and well-draining soil.",
        "image": "https://example.com/anwar-ratol-mango.jpg"
    },{
        "id": 56,
        "name": "Sindhri Chaunsa Mango",
        "species": "Mangifera indica",
        "type": "Fruit",
        "category": "Tropical Fruit",
        "sunlight": "Full Sun",
        "water": "Moderate",
        "soil": "Well-draining",
        "growthRate": "Moderate",
        "origin": "Pakistan/India",
        "generation": "Genus: Mangifera, Family: Anacardiaceae",
        "description": "Sindhri Chaunsa mango combines the sweetness and rich flavor of Chaunsa with the large size and juicy texture of Sindhri. It has a golden-yellow skin and is highly prized for its aromatic, fiberless flesh. The plant requires full sun and well-draining soil to thrive.",
        "image": "https://example.com/sindhri-chaunsa-mango.jpg"
    },{
        "id": 57,
        "name": "White Chaunsa Mango",
        "species": "Mangifera indica",
        "type": "Fruit",
        "category": "Tropical Fruit",
        "sunlight": "Full Sun",
        "water": "Moderate",
        "soil": "Well-draining",
        "growthRate": "Moderate",
        "origin": "Pakistan/India",
        "generation": "Genus: Mangifera, Family: Anacardiaceae",
        "description": "White Chaunsa mango is a variant of the Chaunsa mango, known for its distinctive creamy, pale yellow flesh. It has a sweet, rich flavor with minimal fiber and is highly valued for its smooth, juicy texture. The plant thrives in full sun and well-draining soil.",
        "image": "https://example.com/white-chaunsa-mango.jpg"
    },{
        "id": 58,
        "name": "Kesar Mango",
        "species": "Mangifera indica",
        "type": "Fruit",
        "category": "Tropical Fruit",
        "sunlight": "Full Sun",
        "water": "Moderate",
        "soil": "Well-draining",
        "growthRate": "Moderate",
        "origin": "India",
        "generation": "Genus: Mangifera, Family: Anacardiaceae",
        "description": "Kesar mango, also known as 'Saffron Mango,' is famous for its vibrant orange color, sweet flavor, and rich, creamy texture. It is highly prized in India for its aromatic taste and juicy flesh. The plant thrives in full sun and well-draining soil.",
        "image": "https://example.com/kesar-mango.jpg"
    },{
        "id": 59,
        "name": "Banganapalli Mango",
        "species": "Mangifera indica",
        "type": "Fruit",
        "category": "Tropical Fruit",
        "sunlight": "Full Sun",
        "water": "Moderate",
        "soil": "Well-draining",
        "growthRate": "Moderate",
        "origin": "India",
        "generation": "Genus: Mangifera, Family: Anacardiaceae",
        "description": "Banganapalli mango, also known as 'Banana Mango,' is renowned for its large size, sweet flavor, and smooth, fiberless flesh. It has a golden-yellow skin when ripe and is valued for its juicy, aromatic taste. The plant prefers full sun and well-draining soil.",
        "image": "https://example.com/banganapalli-mango.jpg"
    },{
        "id": 60,
        "name": "Dusheri Chaunsa Mango",
        "species": "Mangifera indica",
        "type": "Fruit",
        "category": "Tropical Fruit",
        "sunlight": "Full Sun",
        "water": "Moderate",
        "soil": "Well-draining",
        "growthRate": "Moderate",
        "origin": "Pakistan/India",
        "generation": "Genus: Mangifera, Family: Anacardiaceae",
        "description": "Dusheri Chaunsa mango is a delightful combination of the sweet, tangy flavor of Dusheri with the rich, creamy texture of Chaunsa. It has a vibrant yellow skin with a hint of red when ripe and is highly valued for its aromatic, fiberless flesh. The plant thrives in full sun and well-draining soil.",
        "image": "https://example.com/dusheri-chaunsa-mango.jpg"
    },{
        "id": 61,
        "name": "Langra Chaunsa Mango",
        "species": "Mangifera indica",
        "type": "Fruit",
        "category": "Tropical Fruit",
        "sunlight": "Full Sun",
        "water": "Moderate",
        "soil": "Well-draining",
        "growthRate": "Moderate",
        "origin": "Pakistan/India",
        "generation": "Genus: Mangifera, Family: Anacardiaceae",
        "description": "Langra Chaunsa mango combines the unique tanginess of Langra with the rich sweetness of Chaunsa. It features a greenish-yellow skin and a smooth, fiberless texture. This mango variety is highly valued for its aromatic flavor and juicy flesh. The plant requires full sun and well-draining soil to thrive.",
        "image": "https://example.com/langra-chaunsa-mango.jpg"
    },{
        "id": 62,
        "name": "Banganapalli Chaunsa Mango",
        "species": "Mangifera indica",
        "type": "Fruit",
        "category": "Tropical Fruit",
        "sunlight": "Full Sun",
        "water": "Moderate",
        "soil": "Well-draining",
        "growthRate": "Moderate",
        "origin": "Pakistan/India",
        "generation": "Genus: Mangifera, Family: Anacardiaceae",
        "description": "Banganapalli Chaunsa mango is a hybrid variety that combines the large size and sweetness of Banganapalli with the rich, creamy texture of Chaunsa. It features a golden-yellow skin with a smooth, fiberless texture and is prized for its aromatic flavor. The plant thrives in full sun and well-draining soil.",
        "image": "https://example.com/banganapalli-chaunsa-mango.jpg"
    },{
        "id": 63,
        "name": "Himsagar Mango",
        "species": "Mangifera indica",
        "type": "Fruit",
        "category": "Tropical Fruit",
        "sunlight": "Full Sun",
        "water": "Moderate",
        "soil": "Well-draining",
        "growthRate": "Moderate",
        "origin": "India",
        "generation": "Genus: Mangifera, Family: Anacardiaceae",
        "description": "Himsagar mango is known for its small size, exceptional sweetness, and aromatic flavor. It has a smooth, fiberless texture and a golden-yellow skin when ripe. This variety is highly prized for its rich taste and minimal fiber. The plant prefers full sun and well-draining soil.",
        "image": "https://example.com/himsagar-mango.jpg"
    },{
        "id": 64,
        "name": "Neelum Mango",
        "species": "Mangifera indica",
        "type": "Fruit",
        "category": "Tropical Fruit",
        "sunlight": "Full Sun",
        "water": "Moderate",
        "soil": "Well-draining",
        "growthRate": "Moderate",
        "origin": "India/Pakistan",
        "generation": "Genus: Mangifera, Family: Anacardiaceae",
        "description": "Neelum mango is renowned for its bright yellow skin and sweet, tangy flavor. It has a smooth, fiberless texture and is highly valued for its juicy and aromatic flesh. The plant thrives in full sun and well-draining soil.",
        "image": "https://example.com/neelum-mango.jpg"
    },{
        "id": 65,
        "name": "Pallo Mango",
        "species": "Mangifera indica",
        "type": "Fruit",
        "category": "Tropical Fruit",
        "sunlight": "Full Sun",
        "water": "Moderate",
        "soil": "Well-draining",
        "growthRate": "Moderate",
        "origin": "India",
        "generation": "Genus: Mangifera, Family: Anacardiaceae",
        "description": "Pallo mango is known for its large size and sweet, juicy flavor. It has a smooth, fiberless texture and a vibrant yellow skin when ripe. This variety is appreciated for its rich taste and is often used in various culinary applications. The plant requires full sun and well-draining soil to thrive.",
        "image": "https://example.com/pallo-mango.jpg"
    },                                                 
]